### ISSUE TITLE
OrganizationとEncounterの一部プロパティのタイプが異なるため検証が失敗する

### ISSUE THREAD

**Issue by iijimam** [miniclub/jsontemplate#3]
以下の内容を修正する[PullRequest](https://github.com/miniclub/jsontemplate/pull/2)をしています。
- OrganizationのExtention.identifier.valueIdentifier.value はStringなのにIntegerで設定している
- Encounter.diagnosis.rankはStringなのにIntegerで設定している。

**Comment by miniclub** [comment]
mergeしました
